export const jwtConstants = {
  secret:
    'GyNpgC2ErYMDAAAACgAAAEcAAAAOAAAALS7RQI-Xg0Gr4wBDJkS_QQMAAAAKAAAARwAAAA4AAAC0HQAAroeUAOJGPgDShpQAWkc-AAIAzwEAAAAA',
};

export const CONFIGURATION_PATTERNS = {
  CONFIGURATION_HELLO: 'CONFIGURATION_HELLO',

  // Servers
  SERVER_CREATE: 'SERVER_CREATE',
  SERVER_FIND_ALL: 'SERVER_FIND_ALL',
  SERVER_FIND_ONE: 'SERVER_FIND_ONE',
  SERVER_UPDATE: 'SERVER_UPDATE',
  SERVER_REMOVE: 'SERVER_REMOVE',
  SERVER_TOKEN_AUTH: 'SERVER_TOKEN_AUTH',
  SERVER_SET_HEADER: 'SERVER_SET_HEADER',
  SERVER_REVOKE: 'SERVER_REVOKE',
  SERVER_GRANT: 'SERVER_GRANT',

  // Rules
  RULE_CREATE: 'RULE_CREATE',
  RULE_FIND_ALL: 'RULE_FIND_ALL',
  RULE_FIND_GLOBAL: 'RULE_FIND_GLOBAL',
  RULE_UPDATE: 'RULE_UPDATE',
  RULE_REMOVE: 'RULE_REMOVE',

  // Gateway Tokens
  GATEWAY_TOKEN_CREATE: 'GATEWAY_TOKEN_CREATE',
  GATEWAY_TOKEN_FIND_ALL: 'GATEWAY_TOKEN_FIND_ALL',
  GATEWAY_TOKEN_REMOVE: 'GATEWAY_TOKEN_REMOVE',

  // Logs
  LOGS_FIND_ALL: 'LOGS_FIND_ALL',
};

export const FINAL_PATTERNS = {
  ...CONFIGURATION_PATTERNS,
};
